language: generic 

sudo: required
services:
    - docker

before_install:
    - docker build -t markemp/docker-react -f Dockerfile.dev .


script:
    - docker run -e CI=true markemp/docker-react npm run test